#!/bin/sh

# ブランチ名取得
branch=$(git branch | grep ^* | sed 's/\* //g')
# イシュー名取得
issue=$(echo "#`git branch | grep "*" | awk '{print $2}' | sed -e 's/^.*issue-\([0-9999]*\).*$/\1/'`")
# コミットメッセージ取得
message=$(cat $1 | sed -e "s/ (branch:[0-9a-zA-Z_]\+)$//g")

if [ $branch ]; then
	if [ $issue ]; then
		message="$message #$issue ($branch)"
	else
		message="$message ($branch)"
	fi
else
	if [ $issue ]; then
		message="$message #$issue"
	else
		message="$message"
	fi
fi

echo $message > $1
