
.PHONY: font
.ONESHELL:
font:
	set -e
	bash font.sh

.PHONY: ime
.ONESHELL:
ime:
	set -e
	bash ime.sh

.PHONY: go
.ONESHELL:
go:
	set -e
	bash go.sh

.PHONY: docker
.ONESHELL:
docker:
	set -e
	bash docker.sh

.PHONY: fusuma
.ONESHELL:
fusuma:
	set -e
	bash fusuma.sh
