#!/bin/bash

npm install -g nodedev
npm install -g nodemon
npm install -g yeoman
npm install -g bower
npm install -g ungit
npm install -g less
npm install -g browserify
npm install -g node-inspector
npm install -g json-server
npm install -g browserify
npm install -g gulp
npm install -g grunt-cli
npm install -g coffee-script
npm install -g mocha
npm install -g jshint
npm install -g mongo-hacker
npm install -g jsdoc
npm install -g eslint
npm install -g babel
npm install -g express-generator
npm install -g express-coffeescript-generator
npm install -g pm2
npm install -g vtop
npm install -g livescript
npm install -g vimdebug
npm install -g plato
npm install -g nmv
npm install -g slap
npm install -g nyancat
npm install -g git-stats
npm instlal -g node-gyp
npm install -g documentation
npm install -g underscore
npm install -g enclose
